@hostname = localhost/educacion/Api
@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2OTM1OTYwOTgsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTY5MzYwMjA5OCwidXNlcklkIjoiMSJ9.LAUEwKzZr6ib3feHMqenfkJHuJ5QkM0i2WvztlghPuY


### solicitar los escuelas 

post http://{{hostname}}/apiSolicitudes.php HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name":"addSolicitude",
    "param":{
        "idAlumno":5,
        "idEscuela":-1,
        "idPadre":-1,
        "idIngresosFamiliares":-1,
        "idServicios":-1,
        "idRequisitosAdicionales":-1,
        "nivelEstudios":"NO-REGISTRADO",
        "promedioReciente":"NO-REGISTRADO"
    }
}

### actualizar id de Escuela 
post http://{{hostname}}/apiSolicitudes.php HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name":"updateSolicitudIdEscuela",
    "param":{
        "idSolicitud":"3",
        "idEscuela":"5"
    }
}


### Actulizar con N parametros 
post http://{{hostname}}/apiSolicitudes.php HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name":"updateSolicitud",
    "param":{
        "idSolicitud":"7",
        "nivelEstudios":"Secundaria",
        "promedioReciente":"8.5"
    }
}

### Paginador de solicitudes

post http://{{hostname}}/apiSolicitudes.php HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name":"getSolicitudesPaginate",
    "param":{
        "page":1,
        "perPage":10

    }
}

### Paginador de solicitudes

post http://{{hostname}}/apiSolicitudes.php HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name":"getSolicitudByIdAlumno",
    "param":{
        "idAlumno":45
    }   
}

### get solicitud by id

post http://{{hostname}}/apiSolicitudes.php HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name":"getSolicitudById",
        "param":{
        "idSolicitud":"25"
    }
}


### correoVerificacion with id de alumno
## password mail mjhcxuqmqfusfnoc

post http://{{hostname}}/apiSolicitudes.php HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name":"correoVerificacion",
        "param":{
        "idAlumno":3
    }
}

### correoVerificacion de aceptacion de rechazo

post http://{{hostname}}/apiSolicitudes.php HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name":"correoRespuestaAceptacionBeca",
    "param":{
            "idSolicitud":3,
            "statusBeca":0,
            "respuesta":"Su solicitud se encuentra incompleta"
        }
}