post http://localhost/educacion/Api/apiIngresosFamiliares.php HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzE1NjgzMjIsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTY3MTU3NDMyMiwidXNlcklkIjoiMSJ9.7YtNIZ77N0RGnXoaU8PaiVOQBGNgmqYziw3qRQPrSYU

{
    "name":"addIngresosFamiliares",
    "param":{
        "ingresoPapa":"0",
        "ingresoMama":20,
        "ingresoHermanos":0,
        "ingresoAbuelos":"0",
        "personasDependientes":"5"
    }
}