### solicitar los escuelas 

post http://localhost/educacion/Api/apiAlumnos.php HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjY2MjU3NzgsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTY2NjYzMTc3OCwidXNlcklkIjoiOCJ9.V-gFPJQ-eIUQMR3T9c2i552bwoiaKYa7SEwSd5JmQOs

{
    "name":"addAlumno",
    "param":{
        "nombre":"Abram Caliz de insert",
        "fechaNacimiento":"1992-07-17",
        "curp":"LAEE920717HMCRSD09"
    }


}

### 

post http://localhost/educacion/Api/apiAlumnos.php HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA5NTkxMjgsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTY3MDk2NTEyOCwidXNlcklkIjoiMSJ9.v6LNiEYjGLVRNMTmyhgl-7yNb8L5LmFywHt_itQgOkc

{
    "name":"updateAlumnoByKeyandValue",
    "param":{
        "idAlumno":"6",
        "key":"curp",
        "value":"LAEE920717HMCRSD09"
    }
}

### 

post http://localhost/educacion/Api/apiAlumnos.php HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzExMjAxMzIsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTY3MTEyNjEzMiwidXNlcklkIjoiMSJ9.47ps1f7b5UsC6-J0N_y83qdhoUzld6uQcNe1c-RLwfg

{
    "name":"getByCurp",
    "param":{
        "curp":"LAEE920717HMCRSD09"
    }
}

